# Generated by Django 3.2.9 on 2021-12-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niceUI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
